name: Generate Snake with Growth

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gerar SVG do Snake
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      - name: Ajustar tamanho do SVG via xmlstarlet
        run: |
          # Exemplo: dobra a escala a cada execução (pode usar ${{ steps.snake.outputs.commit_count }})
          SCALE_FACTOR=2
          WIDTH=$((600 * SCALE_FACTOR))
          HEIGHT=$((110 * SCALE_FACTOR))
          xmlstarlet ed -N ns="http://www.w3.org/2000/svg" \
            -u "//ns:svg/@width" -v "${WIDTH}" \
            -u "//ns:svg/@height" -v "${HEIGHT}" \
            dist/github-snake.svg > dist/github-snake-scaled.svg

      - name: Commit and Push Scaled SVG
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/github-snake-scaled.svg'
          message: 'feat: grow snake graphic'
