name: Generate Snake with Growth

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      - name: Ensure dist directory exists
        run: |
          mkdir -p dist

      - name: Adjust SVG size in-place
        run: |
          xmlstarlet ed --inplace \
            -N ns="http://www.w3.org/2000/svg" \
            -u "//ns:svg/@width" -v "800" \
            -u "//ns:svg/@height" -v "200" \
            dist/github-snake.svg

      - name: Commit and Push Scaled SVG
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/github-snake.svg'
          message: 'feat: grow snake graphic'
